import { app } from '../app-context.js';
import { CUSTOM_STICKERS, PAGE_TITLES } from '../ui/assets.ts';
import {
  ACH_FMT, BACKFILL, BACKFILL_GROUP_KEYS, BACKFILL_GROUP_OF, BACKFILL_GROUPS,
  BASE_DOCS_URL, BBGL_ERROR_CODE, BS_STAT_ROWS, compareVersions, CONSTANTS, ECAN_LOG, ECSTASY_LOG, ENERGY_LOGS, ENERGY_PARAM,
  EX_OD_LOG, GAME, GYM_TIERS, HAPPY_LOGS, ITEM_GROUP_LABELS, ITEM_LOG_META, ITEM_LOGS, KEYS, LAYOUT, LSD_OD_LOG,
  MSG_CLIPBOARD_DENIED, MSG_KEY_FORMAT_INVALID, MSG_KEY_NETWORK_ERROR, MSG_SYNC_NETWORK_ERROR, MSG_SYNC_QUOTA,
  OD_LOGS, r2, SCRIPT_VERSION, STAT_ENHANCER_PARAM, STAT_HAPPY_PARAM, STAT_KEYS, STAT_LOGS, SYNC_FROM_BUFFER,
  TORN_KEY_ERROR_MAP, TRAIN_ENERGY_PARAM, TRAIN_LOGS, WIPE_BELOW_VERSION, XANAX_LOG, XANAX_OD_LOG, ZERO_BREAKDOWN,
  bbglError, tornKeyErrorText
} from '../core/constants.ts';
import { Log, Perf } from '../core/log.ts';
import {
  ALLOWED_CONFIG_KEYS, TAB_ID, calendarState, dom, graphState, historyCache, lastButtonLocation, layoutObservers,
  refreshClickLog, runtime, saveConfig, saveViewState, setHistoryCache, setLastButtonLocation, setTopCeiling, setViewState,
  topCeilingCache, topCeilingTs, userConfig, viewState
} from '../core/state.ts';
import { Formatter, TimeManager, getISOWeek, getWeekKey } from '../domain/time.ts';

function loadStickerData() { const unlocked = runtime.demoMode ? 1 : app.DataController.getUnlockedCount() || 1; const it = []; for (let i = 1; i <= 50; i++) { const c = CUSTOM_STICKERS.find(s => s.id === i); if (c) it.push({ type: 'image', ...c, unlocked: i <= unlocked });else it.push(null); } runtime.stickerData = it; }

function renderStickers() { Perf.start('renderStickers'); if (!runtime.stickerData.length) loadStickerData(); if (runtime.currentStickerPage === -1) { renderSponsorshipPage(); Perf.end('renderStickers'); return; } const sg = document.getElementById('bbgl-sponsor-grid'); if (sg) sg.style.display = 'none'; if (dom.stickerGrid) dom.stickerGrid.style.display = ''; const dc = dom.stickerPagination, te = dom.stickerTitle; if (te) te.innerText = PAGE_TITLES[runtime.currentStickerPage] || ""; const tp = Math.ceil(runtime.stickerData.length / 10), pb = dom.stickerPrev, nb = dom.stickerNext, sb = dom.stickerSponsor; if (pb) { if (runtime.currentStickerPage <= 0) pb.classList.add('disabled');else pb.classList.remove('disabled'); } if (sb) { if (runtime.currentStickerPage === 0) sb.classList.remove('disabled');else sb.classList.add('disabled'); } if (nb) { if (runtime.currentStickerPage >= tp - 1) nb.classList.add('disabled');else nb.classList.remove('disabled'); } if (dc) { dc.innerHTML = ''; const sd = document.createElement('div'); sd.className = 'pg-dot'; sd.onclick = () => { runtime.currentStickerPage = -1; viewState.currentStickerPage = -1; saveViewState(); renderStickers(); }; dc.appendChild(sd); for (let i = 0; i < tp; i++) { const d = document.createElement('div'); d.className = `pg-dot ${i === runtime.currentStickerPage ? 'active' : ''}`; d.onclick = () => { runtime.currentStickerPage = i; renderStickers(); }; dc.appendChild(d); } } const start = runtime.currentStickerPage * 10, pi = runtime.stickerData.slice(start, start + 10); if (runtime.stickerSlots.length === 0) { Perf.end('renderStickers'); return; } let comingSoonDiv = document.getElementById('bbgl-coming-soon'); if (runtime.currentStickerPage >= 2) { for (let i = 0; i < 10; i++) runtime.stickerSlots[i].style.display = 'none'; if (!comingSoonDiv) { const g = document.getElementById('bbgl-sticker-container') || dom.stickerContainer; if (g) { const cs = document.createElement('div'); cs.id = 'bbgl-coming-soon'; cs.className = 'bbgl-coming-soon'; cs.innerHTML = 'Cumming<br>Soon...'; g.appendChild(cs); } } else comingSoonDiv.style.display = 'block'; } else { if (comingSoonDiv) comingSoonDiv.style.display = 'none'; for (let i = 0; i < 10; i++) { const sl = runtime.stickerSlots[i], img = sl.querySelector('.sticker-img'), it = pi[i]; sl.style.display = ''; if (it) { sl.className = 'sticker-slot active-slot'; if (it.unlocked) { sl.classList.add('has-item'); sl.classList.remove('locked'); sl.setAttribute('data-tooltip', `${it.name}`); sl.onclick = () => openItemViewer(it); } else { sl.classList.add('has-item', 'locked'); sl.setAttribute('data-tooltip', app.app.TOOLTIPS.LOCKED); sl.onclick = null; } if (img.src !== it.url) img.src = it.url; } else { sl.className = 'sticker-slot'; sl.onclick = null; } } } Perf.end('renderStickers'); }

function animateViewer(ts) { if (document.hidden || runtime.currentOpenedItemId === null || viewState.subView !== 'stickers' && viewState.subView !== 'viewer' && runtime.currentOpenedItemId === null) { if (runtime.viewerLoopId) cancelAnimationFrame(runtime.viewerLoopId); runtime.viewerLoopId = null; return; } if (!runtime.lastFrameTime) runtime.lastFrameTime = ts; const el = ts - runtime.lastFrameTime; if (el > 17) { runtime.lastFrameTime = ts - el % 17; const ped = dom.viPedestal, obj = dom.viObj; if (ped && obj) { runtime.viewerRotation += runtime.viewerSpeed; ped.style.transform = `rotateY(${runtime.viewerRotation}deg) translateZ(0)`; if (obj.classList.contains('is-image')) { const rad = runtime.viewerRotation * Math.PI / 180, br = (0.7 + Math.sin(rad) * 0.3).toFixed(2), isF = Math.cos(rad) > -0.2 ? 1 : 0; obj.style.setProperty('--sheen-pos', runtime.viewerRotation * 2.5 + '% 0%'); obj.style.setProperty('--back-brightness', br); obj.style.setProperty('--sheen-opacity', isF); } } } runtime.viewerLoopId = requestAnimationFrame(animateViewer); }

document.addEventListener("visibilitychange", () => { if (!document.hidden && runtime.currentOpenedItemId !== null) { if (runtime.viewerLoopId) cancelAnimationFrame(runtime.viewerLoopId); animateViewer(); } });

function openItemViewer(it, sv = true) { if (runtime.currentOpenedItemId === it.id) return; if (sv) { viewState.activeItemId = it.id; saveViewState(); } app.TooltipController.hide(); const v = dom.itemViewer, bp = dom.bottomPanel, nm = dom.viName, ob = dom.viObj, lf = ob.querySelector('.layer-front'), lb = ob.querySelector('.layer-back'), st = document.querySelector('.viewer-stage'); runtime.currentOpenedItemId = it.id; bp.style.setProperty('display', 'none', 'important'); v.classList.add('active'); v.style.setProperty('display', 'flex', 'important'); let ped = dom.viPedestal; if (!ped) { ped = document.createElement('div'); ped.id = 'vi-pedestal-wrapper'; ped.className = 'viewer-pedestal'; st.appendChild(ped); ped.appendChild(ob); dom.viPedestal = ped; } nm.innerText = it.name; if (it.type === 'image') { ob.classList.add('is-image'); ob.style.setProperty('--bg-mask', `url('${it.url}')`); if (lf) lf.style.backgroundImage = `url('${it.url}')`; if (lb) { lb.style.webkitMaskImage = `url('${it.url}')`; lb.style.maskImage = `url('${it.url}')`; } } runtime.viewerRotation = 0; runtime.viewerSpeed = 0.3; if (runtime.viewerLoopId) cancelAnimationFrame(runtime.viewerLoopId); requestAnimationFrame(animateViewer); const spdUp = () => { runtime.viewerSpeed = 3; }, spdDn = () => { runtime.viewerSpeed = 0.3; }; st.onmousedown = spdUp; st.ontouchstart = spdUp; st.onmouseup = spdDn; st.onmouseleave = spdDn; st.ontouchend = spdDn; st.ontouchcancel = spdDn; }

function closeItemViewer(sv = true) { if (sv) { viewState.activeItemId = null; saveViewState(); } runtime.currentOpenedItemId = null; if (runtime.viewerLoopId) { cancelAnimationFrame(runtime.viewerLoopId); runtime.viewerLoopId = null; } const v = dom.itemViewer, bp = dom.bottomPanel; if (v) { v.classList.remove('active'); v.style.setProperty('display', 'none', 'important'); } if (bp) { bp.style.removeProperty('display'); if (getComputedStyle(bp).display === 'none') bp.style.display = 'flex'; } }

function setupStickerGrid() { const g = dom.stickerGrid; if (!g) return; runtime.stickerSlots = []; g.innerHTML = ''; for (let i = 0; i < 10; i++) { const s = document.createElement('div'), m = document.createElement('img'); s.className = 'sticker-slot'; m.className = 'sticker-img'; s.appendChild(m); g.appendChild(s); runtime.stickerSlots.push(s); } const container = dom.stickerContainer; if (container && !document.getElementById('bbgl-sponsor-grid')) { const sg = document.createElement('div'); sg.id = 'bbgl-sponsor-grid'; sg.style.display = 'none'; const pts = getSponsorBurstPoints(); for (let i = 0; i < 3; i++) { const slot = document.createElement('div'); slot.className = 'sticker-slot sticker-slot-sponsor active-slot locked'; const labelText = i === 0 ? 'Corleone Faction<br>Sticker Here ;)' : 'Your Faction<br>Sticker Here'; slot.innerHTML = `<svg class="sponsor-sticker-svg" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg"><polygon points="${pts}" fill="#ffffff"/></svg><span class="sponsor-sticker-label">${labelText}</span>`; sg.appendChild(slot); } const pag = dom.stickerPagination; if (pag && pag.parentElement === container) container.insertBefore(sg, pag);else container.appendChild(sg); } renderStickers(); }

let _sponsorBurstPoints = null;

function getSponsorBurstPoints() { if (_sponsorBurstPoints) return _sponsorBurstPoints; const pts = []; for (let i = 0; i < 20; i++) { const angle = (i * 18 - 90) * Math.PI / 180; const r = i % 2 === 0 ? 48 : 36; const x = (50 + r * Math.cos(angle)).toFixed(2); const y = (50 + r * Math.sin(angle)).toFixed(2); pts.push(`${x},${y}`); } _sponsorBurstPoints = pts.join(' '); return _sponsorBurstPoints; }

function renderSponsorshipPage() { if (dom.stickerTitle) dom.stickerTitle.innerText = "Sponsorship"; if (dom.stickerGrid) dom.stickerGrid.style.display = 'none'; const comingSoon = document.getElementById('bbgl-coming-soon'); if (comingSoon) comingSoon.style.display = 'none'; const sg = document.getElementById('bbgl-sponsor-grid'); if (sg) sg.style.display = 'grid'; if (dom.stickerPrev) dom.stickerPrev.classList.add('disabled'); if (dom.stickerSponsor) dom.stickerSponsor.classList.add('disabled'); if (dom.stickerNext) dom.stickerNext.classList.remove('disabled'); const dc = dom.stickerPagination; if (dc) { dc.innerHTML = ''; const tp = Math.ceil(runtime.stickerData.length / 10); const sd = document.createElement('div'); sd.className = 'pg-dot pg-dot-sponsor active'; sd.onclick = () => { runtime.currentStickerPage = -1; viewState.currentStickerPage = -1; saveViewState(); renderStickers(); }; dc.appendChild(sd); for (let i = 0; i < tp; i++) { const d = document.createElement('div'); d.className = 'pg-dot'; d.onclick = () => { runtime.currentStickerPage = i; viewState.currentStickerPage = i; saveViewState(); renderStickers(); }; dc.appendChild(d); } } }


/**
 *  [SECTION IX] THE MOTIVATION (Init & Event Handling)
 *  ========================================================================
 *  A clean, pure, and sober reason to keep it all going.
 *  Like church, but without the Priest.
 */


function changeStickerPage(d) { if (!userConfig.animations) { viewState.currentStickerPage += d; runtime.currentStickerPage = viewState.currentStickerPage; saveViewState(); renderStickers(); return; } const oldActive = runtime.currentStickerPage === -1 ? document.getElementById('bbgl-sponsor-grid') : dom.stickerGrid, bg = dom.stickerGridBg; if (oldActive) { const ghost = oldActive.cloneNode(true); ghost.style.pointerEvents = 'none'; ghost.style.position = 'absolute'; ghost.style.top = '0'; ghost.style.left = '0'; ghost.style.width = '100%'; ghost.style.animation = d > 0 ? 'bbgl-slide-out-l 0.3s ease forwards' : 'bbgl-slide-out-r 0.3s ease forwards'; oldActive.parentElement.appendChild(ghost); const removeGhost = () => { if (ghost.parentElement) ghost.remove(); }; ghost.addEventListener('animationend', removeGhost, { once: true }); const ghostTimer = setTimeout(removeGhost, 400); ghost.addEventListener('animationend', () => clearTimeout(ghostTimer), { once: true }); } if (bg) { const bgGhost = bg.cloneNode(true); bgGhost.style.pointerEvents = 'none'; bgGhost.style.position = 'absolute'; bgGhost.style.top = '0'; bgGhost.style.left = '0'; bgGhost.style.width = '100%'; bgGhost.style.animation = d > 0 ? 'bbgl-slide-out-l 0.3s ease forwards' : 'bbgl-slide-out-r 0.3s ease forwards'; bg.parentElement.appendChild(bgGhost); const removeBgGhost = () => { if (bgGhost.parentElement) bgGhost.remove(); }; bgGhost.addEventListener('animationend', removeBgGhost, { once: true }); const bgGhostTimer = setTimeout(removeBgGhost, 400); bgGhost.addEventListener('animationend', () => clearTimeout(bgGhostTimer), { once: true }); } viewState.currentStickerPage += d; runtime.currentStickerPage = viewState.currentStickerPage; saveViewState(); renderStickers(); const newActive = runtime.currentStickerPage === -1 ? document.getElementById('bbgl-sponsor-grid') : dom.stickerGrid; if (newActive) { newActive.style.animation = d > 0 ? 'bbgl-slide-in-r 0.3s ease forwards' : 'bbgl-slide-in-l 0.3s ease forwards'; newActive.addEventListener('animationend', () => newActive.style.animation = '', { once: true }); } if (bg) { bg.style.animation = d > 0 ? 'bbgl-slide-in-r 0.3s ease forwards' : 'bbgl-slide-in-l 0.3s ease forwards'; bg.addEventListener('animationend', () => bg.style.animation = '', { once: true }); } }

function closeDropdown(d) { d.classList.remove('show'); d.style.position = ''; d.style.top = ''; d.style.left = ''; d.style.zIndex = ''; }

function openDropdown(d, trigger) { d.style.position = 'fixed'; d.style.top = '0px'; d.style.left = '0px'; d.style.zIndex = '9999999'; d.classList.add('show'); const origin = d.getBoundingClientRect(); const r = trigger.getBoundingClientRect(); d.style.top = r.bottom - origin.top + 2 + 'px'; d.style.left = r.left - origin.left + 'px'; }

function toggleMonthDropdown() { const d = dom.monthDropdown; closeDropdown(dom.yearDropdown); d.innerHTML = ''; CONSTANTS.MONTHS_SHORT.forEach((m, i) => { const x = document.createElement('div'); x.className = `drop-item ${i === calendarState.month ? 'active' : ''}`; x.textContent = m; x.onclick = () => { calendarState.month = i; d.querySelectorAll('.drop-item').forEach(el => el.classList.remove('active')); x.classList.add('active'); closeDropdown(d); app.renderPanelContent(); }; d.appendChild(x); }); if (d.classList.contains('show')) closeDropdown(d);else openDropdown(d, dom.monthTrigger); }

function toggleYearDropdown() { const d = dom.yearDropdown; closeDropdown(dom.monthDropdown); d.innerHTML = ''; const s = app.getActiveHistory(), ys = new Set(); s.history.forEach(z => ys.add(parseInt(z.date.split('-')[0]))); if (s.today.date) ys.add(parseInt(s.today.date.split('-')[0])); Array.from(ys).sort().reverse().forEach(y => { const x = document.createElement('div'); x.className = `drop-item ${y === calendarState.year ? 'active' : ''}`; x.textContent = y; x.onclick = () => { calendarState.year = y; d.querySelectorAll('.drop-item').forEach(el => el.classList.remove('active')); x.classList.add('active'); closeDropdown(d); app.renderPanelContent(); }; d.appendChild(x); }); if (d.classList.contains('show')) closeDropdown(d);else openDropdown(d, dom.yearTrigger); }

function toggleStickerView() { const mp = dom.panel, tb = dom.tallToggle; if (!viewState.isTall && !mp.classList.contains('bbgl-mode-page')) { viewState.isTall = true; if (mp) mp.classList.add('bbgl-tall'); if (tb) tb.innerText = "–"; } viewState.activeItemId = 1; app.switchView('stickers'); setTimeout(() => { if (!runtime.stickerData.length) loadStickerData(); const i = runtime.stickerData.find(x => x.id === (viewState.activeItemId || 1)); if (i) openItemViewer(i, true); }, 400); saveViewState(); }

app.loadStickerData = loadStickerData;
app.renderStickers = renderStickers;
app.animateViewer = animateViewer;
app.openItemViewer = openItemViewer;
app.closeItemViewer = closeItemViewer;
app.setupStickerGrid = setupStickerGrid;
app._sponsorBurstPoints = _sponsorBurstPoints;
app.getSponsorBurstPoints = getSponsorBurstPoints;
app.renderSponsorshipPage = renderSponsorshipPage;
app.changeStickerPage = changeStickerPage;
app.closeDropdown = closeDropdown;
app.openDropdown = openDropdown;
app.toggleMonthDropdown = toggleMonthDropdown;
app.toggleYearDropdown = toggleYearDropdown;
app.toggleStickerView = toggleStickerView;
export { loadStickerData, renderStickers, animateViewer, openItemViewer, closeItemViewer, setupStickerGrid, _sponsorBurstPoints, getSponsorBurstPoints, renderSponsorshipPage, changeStickerPage, closeDropdown, openDropdown, toggleMonthDropdown, toggleYearDropdown, toggleStickerView };
