import { app } from '../app-context.js';
import { CUSTOM_STICKERS, PAGE_TITLES, cdnize } from '../ui/assets.ts';
import { ASSETS, ICONS } from '../ui/icons.ts';
import { injectStyles } from '../ui/styles.ts';
import {
  ACH_FMT, BACKFILL, BACKFILL_GROUP_KEYS, BACKFILL_GROUP_OF, BACKFILL_GROUPS,
  BASE_DOCS_URL, BBGL_ERROR_CODE, BS_STAT_ROWS, compareVersions, CONSTANTS, ECAN_LOG, ECSTASY_LOG, ENERGY_LOGS, ENERGY_PARAM,
  EX_OD_LOG, GAME, GYM_TIERS, HAPPY_LOGS, ITEM_GROUP_LABELS, ITEM_LOG_META, ITEM_LOGS, KEYS, LAYOUT, LSD_OD_LOG,
  MSG_CLIPBOARD_DENIED, MSG_KEY_FORMAT_INVALID, MSG_KEY_NETWORK_ERROR, MSG_SYNC_NETWORK_ERROR, MSG_SYNC_QUOTA,
  OD_LOGS, r2, SCRIPT_VERSION, STAT_ENHANCER_PARAM, STAT_HAPPY_PARAM, STAT_KEYS, STAT_LOGS, SYNC_FROM_BUFFER,
  TORN_KEY_ERROR_MAP, TRAIN_ENERGY_PARAM, TRAIN_LOGS, WIPE_BELOW_VERSION, XANAX_LOG, XANAX_OD_LOG, ZERO_BREAKDOWN,
  bbglError, tornKeyErrorText
} from '../core/constants.ts';
import { Log, Perf, isDevMode } from '../core/log.ts';
import {
  ALLOWED_CONFIG_KEYS, TAB_ID, calendarState, dom, graphState, historyCache, lastButtonLocation, layoutObservers,
  refreshClickLog, runtime, saveConfig, saveViewState, setHistoryCache, setLastButtonLocation, setTopCeiling, setViewState,
  topCeilingCache, topCeilingTs, userConfig, viewState
} from '../core/state.ts';
import { Formatter, TimeManager, getISOWeek, getWeekKey } from '../domain/time.ts';
import { classifyDay, computeWeekCapsules, computeWeekCompletion, placeCapsuleUnit } from '../domain/capsules.ts';
import { atrophyTitle, calculateLevelProgress, computeDailyLevelExp, computeLevelExpCost } from '../domain/leveling.ts';
import { findHappyJumps, initializeDayObject, normalizeApiLogs, sumStats } from '../domain/day.ts';


const TooltipController = { el: null, arrow: null, currentTarget: null, init() { if (this.el) return; this.el = document.createElement('div'); this.el.id = 'bbgl-tooltip'; this.arrow = document.createElement('div'); this.arrow.id = 'bbgl-tooltip-arrow'; this.el.appendChild(this.arrow); document.body.appendChild(this.el); }, hide() { if (this.el) { this.el.style.display = 'none'; this.currentTarget = null; } }, show(html, rect, forceSide) { if (!this.el) this.init(); this.el.innerHTML = html; this.el.appendChild(this.arrow); this.el.style.display = 'block'; this.el.className = ''; const ttRect = this.el.getBoundingClientRect(), pad = 12, view = { w: window.innerWidth, h: window.innerHeight }; let side = 'top'; const fitsTop = rect.top - ttRect.height - pad >= 0, fitsBot = rect.bottom + ttRect.height + pad <= view.h; if (forceSide) side = forceSide;else if (fitsTop) side = 'top';else if (fitsBot) side = 'bottom';else side = 'left'; let x = 0, y = 0; if (side === 'top') { x = rect.left + rect.width / 2 - ttRect.width / 2; y = rect.top - ttRect.height - pad; } else if (side === 'bottom') { x = rect.left + rect.width / 2 - ttRect.width / 2; y = rect.bottom + pad; } else { x = rect.left - ttRect.width - pad; y = rect.top + rect.height / 2 - ttRect.height / 2; } if (x < 5) x = 5; if (x + ttRect.width > view.w - 5) x = view.w - ttRect.width - 5; if (y < 5) y = 5; if (y + ttRect.height > view.h - 5) y = view.h - ttRect.height - 5; this.el.style.left = x + 'px'; this.el.style.top = y + 'px'; this.el.classList.add('pos-' + side); this.arrow.style.marginLeft = ''; this.arrow.style.marginTop = ''; }, resolve(target) { return target.closest('[data-tooltip], [data-tooltip-html]'); }, handleHover(e) { const t = this.resolve(e.target); if (!t) { if (this.currentTarget) this.hide(); return; } if (this.currentTarget === t) return; this.currentTarget = t; const h = t.getAttribute('data-tooltip-html'), txt = t.getAttribute('data-tooltip'); const side = t.getAttribute('data-tooltip-side') || undefined; const anchorSel = t.getAttribute('data-tooltip-anchor'); let rect; if (anchorSel) { const anchor = t.closest('.bbgl-weekly-anchor')?.querySelector(anchorSel); if (anchor) { const r = anchor.getBoundingClientRect(); const activeH = parseFloat(getComputedStyle(anchor).getPropertyValue('--bbgl-handle-active-h')) || 32; rect = { left: r.left, width: r.width, bottom: r.bottom, top: r.bottom - activeH, height: activeH }; } else { rect = t.getBoundingClientRect(); } } else { rect = t.getBoundingClientRect(); } if (h) this.show(h, rect, side);else if (txt) this.show('<div style="text-align:center; color:#ddd;">' + txt + '</div>', t.getBoundingClientRect(), side);else this.hide(); } };

function generateRichTooltip(sl) { const f = Formatter.abbr, fg = n => (n > 0 ? '+' : '') + f(n), s = sl.stats; const MOS = CONSTANTS.MONTHS_SHORT; let lbl; if (sl.resolution === 'DAY') { const d = Formatter.parse(sl.date); lbl = `${MOS[d.getUTCMonth()]} ${d.getUTCDate()} • ${d.getUTCFullYear()}`; } else if (sl.resolution === 'WEEK') { if (sl._weekStart && sl._weekEnd) { const dS = Formatter.parse(sl._weekStart); lbl = `Week of ${MOS[dS.getUTCMonth()]} ${dS.getUTCDate()} • ${dS.getUTCFullYear()}`; } else { lbl = sl.label || Formatter.datePretty(sl.date); } } else if (sl.resolution === 'MONTH') { const mIdx = CONSTANTS.MONTHS.indexOf(sl.label); const year = sl._dailyList && sl._dailyList.length > 0 ? sl._dailyList[0].date.slice(0, 4) : sl.date ? sl.date.slice(0, 4) : String(calendarState.year); lbl = `${mIdx >= 0 ? MOS[mIdx] : sl.label} • ${year}`; } else if (sl.resolution === 'YEAR') { const days = sl._dailyList ? sl._dailyList.filter(d => d.eSpent && d.eSpent.total > 0).length : 0; lbl = `${days} Day${days !== 1 ? 's' : ''} • ${sl.label}`; } else { lbl = Formatter.datePretty(sl.label || sl.date); } let h = `<div class="tt-header">${lbl}</div><div class="tt-energy" style="margin-bottom:6px; padding-bottom:4px; border-bottom:1px solid #555;">Energy: ${Formatter.number(s.total.cost)}</div><div style="display:grid; grid-template-columns: 28px 1fr 1fr 1fr; column-gap:10px; row-gap:2px; font-family:'Arial', sans-serif; font-size:11px;">`; const hs = "color:#666; font-size:9px; text-align:right; margin-bottom:2px;"; h += `<div style="grid-column:2; ${hs}">Start</div><div style="grid-column:3; ${hs}">Gain</div><div style="grid-column:4; ${hs}">End</div>`; const r = (n, c, o, t = false) => { const st = t ? "border-top:1px solid #444; padding-top:4px; margin-top:2px;" : ""; return `<div style="color:${c}; font-weight:700; ${st}">${n}</div><div style="text-align:right; color:#888; ${st}">${f(o.start)}</div><div style="text-align:right; color:${CONSTANTS.COLORS.GAINS}; font-weight:700; ${st}">${fg(o.gain)}</div><div style="text-align:right; color:#fff; font-weight:700; ${st}">${f(o.end)}</div>`; }; h += r('STR', CONSTANTS.COLORS.STR, s.str) + r('DEF', CONSTANTS.COLORS.DEF, s.def) + r('SPD', CONSTANTS.COLORS.SPD, s.spd) + r('DEX', CONSTANTS.COLORS.DEX, s.dex) + r('TOT', CONSTANTS.COLORS.TOT, s.total, true); return h + `</div>`; }

function updateFooterTooltip() { const b = document.getElementById('bbgl-gym-tab'); if (!b) return; const isP = document.body.classList.contains('bbgl-page-mode-active'); const txt = isP ? 'Disabled while viewing the log in Page View' : 'Big Black Gym Log'; if (b.getAttribute('data-tooltip') !== txt) b.setAttribute('data-tooltip', txt); }

app.TooltipController = TooltipController;
app.generateRichTooltip = generateRichTooltip;
app.updateFooterTooltip = updateFooterTooltip;
export { TooltipController, generateRichTooltip, updateFooterTooltip };
